language: generic
dist: xenial
sudo: required
script:
- bash test.sh
deploy:
  provider: releases
  api_key:
    secure: JPzjgxNHaRneEK0R+CgdFOc0/ZPoTmd2oMgNrTYMWp2ts/433Y30WnO7AEk5Ab4JR/Q9jNPpjtSi8+7k1KpKMeF9gVqbQzobI9c+P7WlztFZWOEiozZNXUVvNoVHpga1FeDoAO52XhcoEiYtTIMJPOQwMDKNDMf5C0+JzvzwQ7hL797o5kmzUAlthWE7YlyYUFEzAGyeULcmmJacPlKT4+6KJzF7x1xQzarCpJV2KcTbh320wajSisuQ7P/Bp4VDlG/mbQriQBv/HNH2MIzNQNOv67FD8oSDeBPU8XOoDcOxqeQPjhpKFrCWfhx6aLDbKtRcHVGjGrI6+TBXKDoJ13EgeBRuucqI3nGEDR8og0LymRyeZ7FkYcno8Pwqdb7e0wxwjg0f6t0fx4CosjStl2H1gTwayo65d9Q0RdUa0k7DALOlbhk9cebM4NdCrA496FZ5nPZXJ/dOJ16/tMP6DmF8twpa7hYmgJY8CIe2nYCxFM/DfbBcQ511uXPakXngknHdsV43Ke+pNH5R8pfReh2JTRxpy/QmPdNLAWsfkUM5kjd86pkn27jlcCNmFOdWGXQ6UiLWNn80Zxla0XthOLGTZi3+ikXftleMz9/Rz450vG9wX1NDd/JJCdcQWARv3C7rY4cexqxN7a5aXZNhEpyVjy+1iWAvXM4wnS7WAdg=
  file: hello.sh
  on:
    repo: berchev/hello_project
    tags: true
